# RAG Settings
rag:
  data_type: "clip"       # Type of data processing (e.g., 'clip', 'raw')

caption:
  fps: 1

model:
  name: "EgoGPT"
  params:
    pretrained: "lmms-lab/EgoGPT-7b-EgoIT-EgoLife"

