# RAG Settings
rag:
  data_type: "clip"       # Type of data processing (e.g., 'clip', 'raw')

caption:
  fps: 1
  
model:
  name: "ixc2_5"
  params:
    pretrained: "internlm/internlm-xcomposer2d5-7b"