# RAG Settings
rag:
  data_type: "clip"       # Type of data processing (e.g., 'clip', 'raw')

video:
  fps: 1
  max_frames_num: 32

model:
  name: "EgoGPT"
  params:
    pretrained: "/mnt/sfs-common/jkyang/EgoGPT/checkpoints/egogpt_IT_12k_1127"

