# RAG Settings
rag:
  data_type: "clip"       # Type of data processing (e.g., 'clip', 'raw')

caption:
  fps: 1

model:
  name: "EgoGPT"
  params:
    pretrained: "/mnt/sfs-common/jkyang/EgoGPT/checkpoints/EgoGPT-llavaov-7b-EgoIT-109k-release"

